version: '3.7'
services:
  mongodb:
  extends:
    file: docker-compose.yml
    service: mongodb

  go_testing:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example_password
      MONGO_DB: ecfmp_test
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      AUTH_JWT_PUBLIC_KEY_FILE: './docker/dev_public_key.pub'
      AUTH_JWT_PRIVATE_KEY_FILE: './docker/dev_private_key.pem'
      AUTH_JWT_AUDIENCE: 'ecfmp-discord-dev'
      LOG_LEVEL: "FATAL"
    volumes:
      - .:/app
    networks:
      - default
