ARG GO_VERSION
FROM golang:${GO_VERSION}-alpine AS builder_base

WORKDIR /app

# Install GRPC health probe
RUN set -ex \
    && apk add --no-cache curl \
    && curl -fSL https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.19/grpc_health_probe-linux-amd64 -o /usr/local/bin/grpc_health_probe \
    && chmod +x /usr/local/bin/grpc_health_probe

# Create the user
RUN adduser -u1000 -D appuser

USER appuser

FROM builder_base AS testing

# We check if a file exists in /tmp/health.txt to see if the container is healthy
HEALTHCHECK --interval=5s --timeout=3s --start-period=5s --retries=3 CMD [ "sh", "-c", "[ -f /tmp/health.txt ]"]

ENTRYPOINT [ "./docker/test-container.sh" ]

# Dev container, uses air for hot reloading
FROM builder_base AS development

HEALTHCHECK --interval=5s --timeout=3s --start-period=5s --retries=3 CMD [ "grpc_health_probe", "-addr", "localhost:80", "-connect-timeout", "250ms", "-rpc-timeout", "100ms" ]

RUN go install github.com/cosmtrek/air@latest

ENTRYPOINT ["./docker/dev-container.sh"]
