version: "3.7"
services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - GO_VERSION=1.21
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example_password
      MONGO_DB: ecfmp
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      AUTH_JWT_PUBLIC_KEY_FILE: "./docker/dev_public_key.pub"
      AUTH_JWT_AUDIENCE: "ecfmp-discord-dev"
      LOG_LEVEL: "TRACE"
      ENV_FILE: "./.env"
    ports:
      - "8080:80"
    volumes:
      - .:/app
    networks:
      - default
    healthcheck:
      interval: 1s
      timeout: 5s
      retries: 100
      start_period: 30s

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    logging:
      driver: none
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    networks:
      - default

volumes:
  mongodb_data:

networks:
  default:
    name: ecfmp
