version: "3.7"
services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: development
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example_password
      MONGO_DB: ecfmp
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID} # This is the testing webhook channel
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      AUTH_JWT_PUBLIC_KEY_FILE: './docker/dev_public_key.pub'
      AUTH_JWT_AUDIENCE: 'ecfmp-discord-dev'
    ports:
      - "8080:80"
    volumes:
      - .:/app
    networks:
      - default

  go_testing:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: testing
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example_password
      MONGO_DB: ecfmp_test
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      AUTH_JWT_PUBLIC_KEY_FILE: './docker/dev_public_key.pub'
      AUTH_JWT_PRIVATE_KEY_FILE: './docker/dev_private_key.pem'
      AUTH_JWT_AUDIENCE: 'ecfmp-discord-dev'
    volumes:
      - .:/app
    networks:
      - default

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-entry/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    networks:
      - default

volumes:
  mongodb_data:

networks:
  default:
    name: ecfmp
