FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download
COPY *.go ./
RUN go install github.com/cosmtrek/air@latest

RUN go build -o /ecfmp-discord

EXPOSE 80

CMD ["air", "-c", ".air.toml"]
