name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Start containers
        run: docker compose up -d --build --wait go_testing

      - name: Run Tests
        run: make test

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Format
        run: go fmt ./...

  vet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Vet
        run: go vet ./...
