name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Build Protobuf
        run: make protobuf

      - name: Copy Env
        run: cp .env.example .env

      - name: Start Containers
        run: docker compose --file docker-compose-ci.yml up --build -d --wait --wait-timeout 30

      - name: Run Tests
        run: docker compose exec go_testing go test -v ./...

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format
        run: go fmt ./...

  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Build Protobuf
        run: make protobuf

      - name: Vet
        run: go vet ./...

  build-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Build Production Container
        run: make build_production
