name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Build Protobuf
        run: make protobuf

      - name: Copy Env
        run: cp .env.example .env

      - name: Start containers
        run: docker compose up -d --build --wait discord mongodb

      # Collect logs from the discord container even if it fails
      - name: Collect Logs
        if: ${{ always() }}
        run: docker logs

      - name: Run Tests
        run: make test

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format
        run: go fmt ./...

  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Build Protobuf
        run: make protobuf

      - name: Vet
        run: go vet ./...

  build-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Build Production Container
        run: make build_production
