name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Build Protobuf
        run: make protobuf

      - name: Start containers
        run: docker compose up -d --build --wait go_testing

      - name: Run Tests
        run: make test
