name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup-protobuf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROTOBUF_TOKEN }}
          submodules: true

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Check Protoc version
        run: protoc --version

      - name: Install Go Proto Packages
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Make Proto
        run: make protobuf

  test:
    runs-on: ubuntu-latest
    needs: setup-protobuf
    steps:
      - name: Start containers
        run: |
          ls -la
          docker compose up -d --build --wait go_testing

      - name: Run Tests
        run: make test

  format:
    runs-on: ubuntu-latest
    needs: setup-protobuf
    steps:
      - name: Format
        run: go fmt ./...

  vet:
    runs-on: ubuntu-latest
    needs: setup-protobuf
    steps:
      - name: Vet
        run: go vet ./...
